### ISSUE TITLE
both cdis.cdi.kubevirt.io and cdi namespace can not be deleted from v1.31.0

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/containerized-data-importer#1683]
/kind bug

**What happened**:

cdi crd can not be deleted

$  kubectl describe customresourcedefinition.apiextensions.k8s.io  cdis.cdi.kubevirt.io

...<snip>..

Status:
  Accepted Names:
    Kind:       CDI
    List Kind:  CDIList
    Plural:     cdis
    Short Names:
      cdi
      cdis
    Singular:  cdi
  Conditions:
    Last Transition Time:  2021-03-02T07:12:41Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-03-02T07:12:41Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2021-03-02T12:10:23Z
    Message:               CustomResource deletion is in progress
    Reason:                InstanceDeletionInProgress
    Status:                True
    Type:                  Terminating  <---- Stuck in Terminating status
  Stored Versions:
    v1beta1

$ kubectl get ns
NAME              STATUS        AGE
cdi               Terminating   5h24m

**What you expected to happen**:
crd and namespace can be deleted

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.31.0
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Did you delete the CDI CR first? The order to delete CDI is:
kubectl delete cdi cdi
wait for the operator to delete all the objects.
kubectl delete ns cdi

If you don't delete the CDI CR first then if you delete the CDI namespace, the api server might get deleted in the wrong order and it won't be able to properly delete other resources.

**Comment by yangxiaoliang** [comment]
> Did you delete the CDI CR first? The order to delete CDI is:
> kubectl delete cdi cdi
> wait for the operator to delete all the objects.
> kubectl delete ns cdi
> 
> If you don't delete the CDI CR first then if you delete the CDI namespace, the api server might get deleted in the wrong order and it won't be able to properly delete other resources.

Thanks @awels

**Comment by SilverSoldier** [comment]
I was getting a similar issue with v1.27. I started deleting in the wrong order and both the CRD and namespace were stuck at terminating state. Listing the steps I took, in case it helps someone or to check if there is a better fix.

1. First I followed the [fix](https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-369099998) from a Kubernetes issue to remove the `customresourcecleanup.apiextensions.k8s.io` finalizer from the CRD. (Got the link from this [SO answer](https://stackoverflow.com/a/52012367))
  ```
  kubectl patch crd/cdis.cdi.kubevirt.io -p '{"metadata":{"finalizers":[]}}' --type=merge
  kubectl delete crd/cdis.cdi.kubevirt.io -n cdi
  ```
2. That helped to delete the CRD but the namespace was stuck at terminating, with the error `unable to retrieve the complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the server is currently unable to handle the request` since the APIServer was deleted (Which is what I think awels@ mentioned as "the api server might get deleted in the wrong order and it won't be able to properly delete other resources").

   To fix that, I followed the instructions for manually deleting namespace stuck in terminating state from [here](https://www.ibm.com/support/knowledgecenter/SSBS6K_3.2.x/troubleshoot/ns_terminating.html) for the `cdi` namespace. (Instructions are well written there, so I am not listing them here.)

**Comment by Davo911** [comment]
Had the same Issue, but not even the [IBM Guide on stucked namespace](https://www.ibm.com/docs/en/cloud-private/3.2.x?topic=console-namespace-is-stuck-in-terminating-state) helped.
The only way to resolve for me was to:

```bash
kubectl proxy &
kubectl get namespace cdi -o json |jq '.spec = {"finalizers":[]}' >temp.json
curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/cdi/finalize
```

Maybe this also helps someone.
