### ISSUE TITLE
[Enhancement] Support resizing DataVolumes

### ISSUE THREAD

**Issue by weihanglo** [kubevirt/containerized-data-importer#1858]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

Support resizing DataVolumes (a.k.a. volume expansion)

**What you expected to happen**:

Modification of `dv.spec.pvc.resources.requests.stoage` should be accepted, and the embedded PVC resizes along with the change.

**Anything else we need to know?**:

In current implementation, once a DataVolume being created, it goes into a frozen state and [rejects any further `spec` changes][1]. The doc of DataVolume also states that this consistent state let consumers make assumptions about DataVolumes in order to handle their own orchestration, which is reasonable but somehow limited.

If one wants to expand the actual size of a DataVolume attached to a VM, one can edit the embedded PVC, but the change won't reflect to the DataVolume which remains the old size. It would be flexible if we support volume expansion on DataVolumes.

There is also [an online size PR for reflecting PVC expansion][2]. I think both this enhancement and that PR can benefit the data volume usability.  

[1]: https://github.com/kubevirt/containerized-data-importer/blob/2f21a3654588e084d5d89a77874602c5804cfec6/pkg/apiserver/webhooks/datavolume-validate.go#L367-L376
[2]: https://github.com/kubevirt/kubevirt/pull/5981

**Comment by weihanglo** [comment]
If this is a practical feature request, I can help with some guidance from the maintainers.

**Comment by vasiliy-ul** [comment]
ping, @awels . what do you think? this seems like a practical feature and the Harvester team can also contribute to it. would it be a valid enhancement for CDI?

**Comment by awels** [comment]
So we currently have a PR up for what we call 'online' resize: https://github.com/kubevirt/kubevirt/pull/5981 Is that what you are looking for, or do you want to resize DVs that are not associated with a VM at this point?

**Comment by weihanglo** [comment]
> So your issue is that the value in the DV is not updated to match the resize of the underlying PVC?

Thanks for your reply. That's exactly what we want to resolve! A DV's size should be synchronized with underlying PVC. 

Moreover, since the PVC is embedded in a DV, it's good to prevent a user from modifying the size of a PVC directly. It would be even better if one can modify the size of a DV and then get a resized volume/PVC. 

I know it may break the consensus that a DV.spec never change after creation. Therefore, we also seek existing mechanism to inform DV for PVC resizing, but AFAIK "online resize" PR does not address that.

**Comment by awels** [comment]
Okay now that I understand what you want, I can properly address it.

In essence a DV is a precursor to a populator (new feature coming to k8s in the near future). It is basically a recipe that tells CDI what to do to create and populate a PVC. Once the PVC has been created and populated the role of the DV is done. This is the main reason we don't allow modifying the DV, after it has been created, as it serves no purpose anymore.

That being said, I see that being able to modify the size in the DV would cause a resize on the matching PVC would be a benefit. There are a few things we need to consider there.
1. We just added [Storage Profile](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/storageprofile.md) which allow you to specify at a storage level your preferred accessMode/Volume Mode/File system overhead. In particular we use the file system overhead to increase the size of the created PVC to ensure that the PVC is large enough to hold the disk image including the overhead. This should be fairly simple to accommodate.
2. @maya-r who created https://github.com/kubevirt/kubevirt/pull/5981 to a look at 'offline' resize and found that the PVC is not actually resized until it is being used by a POD IIRC. So that is something to consider.
3. We need to define what it means to modify a DV that has been completed. Its purpose is finished at that point, so modifying it should have a clear definition of what that means.
