### ISSUE TITLE
Run e2e test on ARM64

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/containerized-data-importer#1959]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

**What happened**:
Recode tasks we need to do to enable e2e test on ARM64

Here are some gaps:
1. images does not support arm64, and these images are not from kubevirt project
    quay.io/kubevirt/minio:RELEASE.2018-08-02T23-11-36Z
    quay.io/kubevirt/imageiotest:v0.0.1
    quay.io/kubevirt/fakeovirt:v1.38.0

2. The external provider does not support functional tests, any specific reason for this? (Correct me, if my understanding is wrong)
https://github.com/kubevirt/containerized-data-importer/blob/61684d3d9c07172a687b90bd4b1542f9d6d6a707/cluster-sync/sync.sh#L121

3. For both hpp storage and ceph of external provider, there are some images that are not support arm64. Need to make desition on supporting which storage on ARM64.

**Comment by awels** [comment]
minio is for testing s3, it does look like there are arm versions of the container here https://hub.docker.com/r/minio/minio/tags?page=1&ordering=last_updated, unfortunately that is dockerhub, so we would have to copy an arm version to the quay repo.

The imageiotest and fakeovirt are for one or two tests that specifically test imports from oVirt. The tests are very similar to the tests that import from VMWare, which we already skip since there is no arm version of that. So I see no reason to not skip those also.

So the external provider we usually use to deploy development versions onto a cluster that is otherwise already full configured with storage and everything we need (we also don't want to install stuff on an external cluster that the user didn't specifically ask for). The storage we configure for kubevirtci runs is specific to kubevirtci (paths, number of replicas, etc) which is why we decided to not deploy storage on external clusters.

When we run CI on external clusters, we have some jobs that configure the cluster and install all things needed ahead of time before running the actual tests.

**Comment by awels** [comment]
1. Yes an external cluster makes total sense. You might have noticed that we release a test binary with each release that people can use to run tests against external clusters. All that needs to happen is to pass a KUBECONFIG as an argument to the binary. make build-functest should build that binary and leave it in _out/tests. https://github.com/kubevirt/containerized-data-importer/blob/main/hack/build/build-functest.sh is the script that is called. So to setup a fully functional test run you can have an external cluster, build the binary, and call the binary with a kubeconfig and it should work.

For storage there are more arguments you can pass the binary, you can pass it storage class which provides block volumes, csi clone, and csi snapshots. The arguments are set during cluster-sync based some environment variables. But you can provide them directly to the binary as well. They are defined [here](https://github.com/kubevirt/containerized-data-importer/blob/main/hack/build/run-functional-tests.sh#L63-L71).

In short for your case I would build the binary, and call it with the appropriate arguments for your external cluster. If the storage you have in your cluster does not provide block or snapshot or csi clone, set the argument to blank, and if a test requires it, it will skip the test if it cannot find the storage class (and a blank storage class doesn't exist).
2. If you want a minimum test suite, I would start with https://github.com/kubevirt/containerized-data-importer/blob/main/tests/datavolume_test.go#L239 . The binary described above is a gingko test binary, and takes gingko arguments, you can add focus as an argument and specify a regex for tests you want to focus on. All the entries of that table have a test_id:<number> in their name so if you want to focus one of those tests just use test_id:<number> for the test you are interested in and it should run just that test. Since it is a regex you can focus multiple with test_id:<number>|test_id:<number2> etc.

**Comment by awels** [comment]
One thing to note, a PR just merged that changes the 'master_url' to 'main_url' so that will change with the next release.

**Comment by zhlhahaha** [comment]
Hi Alexander, so what I need to do is 
1. enable a basic storage class on the ARM cluster,
2. run `make cluster-sync` to deploy CDI on ARM cluster and run `make build-functest` to build functest binary
3. pass the correct parameter (like kubeconfig, BLOCK_SC, and other storage I have) to the `run-functional-tests.sh`

Right?

**Comment by awels** [comment]
make cluster-sync will not deploy the yamls for the supporting containers, you will have to do that yourself. Note that run-functional-tests.sh just calls the binary with the provided arguments (it also checks to make sure all the pods are ready before attempting to start the test), so if it is easier for you, you can run call the binary with the right arguments yourself.
