### ISSUE TITLE
add storageclass to golden-pvc example 

### ISSUE THREAD

**Issue by nellyc** [kubevirt/containerized-data-importer#221]
I think it will be good to add the storageclass (marked as optional) to the example file
manifests/example/golden-pvc.yaml

it would be extra nice to have at least some of the available values there as well,
i keep forgetting how to mark glusterfs :)

**Comment by jeffvance** [comment]
@nellyc We don't include storage class details for CDI purposely because we think that this detail is up to the cluster/storage admin. This is the person who creates storage classes and decides what the default SC will be. It seems that if we include specific SCs for gluster then would we also need to include sample SCs for all of the popular storage provisioners?

**Comment by nellyc** [comment]
@jeffvance you can skip the values if you dont think its valuable, 
but i think that adding the field itself and marking it as optional, will show users, who would like to control that, how to do it
it will just make it a more complete example

**Comment by jeffvance** [comment]
Agree. We'll add the storageClass field with a value of "standard" (default).
