### ISSUE TITLE
 [flaky] Image io tests 3937 and 5078

### ISSUE THREAD

**Issue by brybacki** [kubevirt/containerized-data-importer#2229]
**What happened**:

Two imageio tests fail pretty frequently blocking other development.
There is a real bug or a test problem and this needs to be investigated.

Temporarily marked as Pedning.
https://github.com/kubevirt/containerized-data-importer/pull/2228

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
The problem seems to be that there is a race somewhere, and it is possible for the import controller to think the migration is complete while it is simply waiting for the next delta. The import controller doesn't create the next pod, and it is stuck.
(thx @awels)

We have a few more, which I didn't catch failing in past few days:
`3936, 3944`
Wonder if they can trigger the same issue.
