### ISSUE TITLE
Why we need ScratchSpaceStorageClass?

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/containerized-data-importer#2460]
**Is your feature request related to a problem? Please describe**:

When we upload an image cdi will create scratchPVC, and the logic in the code seens that if we have a default sc in the cluster, the ScratchSpaceStorageClass will set as the default sc. Meanwhile we have set StorageClassName in yaml of dv. In my opinion, ScratchSpaceStorageClass may lead to potential error because we usually only care about the sc set in dv yaml run properly and ignore the default sc.

**Describe the solution you'd like**:

Set StorageClassName of dv as the priority sc for scratchPVC. Default sc in the cluster as the second choice.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by awels** [comment]
So to give you some background on the scratch space.
There are some operations that we need scratch space because for whatever reason we cannot convert the image in a streaming fashion. Usually if the image file is gzipped (gzip has the size at the end of the stream). So we have to create some temporary space and store the file there before we can convert it to the target.

Now the idea behind the scratchSpaceStorageClass is that you don't always want to use the storage class of the DV for the scratch space. Lets say you are importing into expensive nvme storage and you don't have a lot of it. In that scenario it makes sense to set your scratch space to slower but cheaper storage, as it will not be used after the import is completed.

We decided if not specified to use the default storage class for this assuming that the default storage class is available for basically everyone in the cluster and should be plentiful. We do allow one to override the scratchspace storage class in case our assumption did not hold.

**Comment by Longchuanzheng** [comment]
> We do allow one to override the scratchspace storage class in case our assumption did not hold.

**Comment by awels** [comment]
If you installed with the operator you can set the value in the CDI CR, if you didn't you can set it in the CDIConfig. https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md

**Comment by Longchuanzheng** [comment]
It works. Thank you for your help : ).
