### ISSUE TITLE
About use pullmethod from node

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/containerized-data-importer#3074]
If you use datavolume, can pull the mirror of the private mirror repository? And this private repository is https.

Use config
pullMethod: node

**Comment by awels** [comment]
pullMethod node uses the node to pull the image, so if the node is configured to connect to the repository, then pullMethod node should work. But I am not entirely sure what the question is.

**Comment by mzzgaopeng** [comment]
> pullMethod node uses the node to pull the image, so if the node is configured to connect to the repository, then pullMethod node should work. But I am not entirely sure what the question is.

If my image is stored in https harbor and the project is a private project, can I use the pullmethod node configuration? If so how should I use it?

**Comment by awels** [comment]
I don't know what `https harbor` means. But in order for you to use `pullMethod: node` your nodes need to be able to pull the container from the registry. So if you can start a pod that uses a container from that registry, then your node can pull from that registry, and the `pullMethod: node` will work, since all we do is start a pod with 2 containers, one with the source and a server, and one with the cdi client that connects to that server.
