### ISSUE TITLE
data volume storage size doesn't match the pvc storage size

### ISSUE THREAD

**Issue by jmccormick2001** [kubevirt/containerized-data-importer#3208]
**What happened**:
I create a DataVolume, specifying the following:
`apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "fedora-iscsi"
spec:
  storage:
    resources:
      requests:
        storage: "6442450944"
    storageClassName: ibox-iscsi
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz"
`

The PVC created by cdi is the following:
`spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "6817408407"
  storageClassName: ibox-iscsi
  volumeMode: Filesystem
status:
  phase: Pending
`

**What you expected to happen**:
I expected the storage sizes to match between DataVolume and PVC.

**How to reproduce it (as minimally and precisely as possible)**:
Create a DataVolume, then look at the size on the PVC that is created.

**Additional context**:
I'm seeing this issue if I enter a hard byte count like above, or '5Gi', or '5G', the PVC has a different value.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): openshift 4.15.5 / kube 1.28.7
- DV specification: see above
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): openshift rhcos
- Kernel (e.g. `uname -a`): N/A
- Install tools: installed via openshift installation
- Others: N/A

**Comment by awels** [comment]
This is expected for filesystem volumes. And can be tuned with the `fileystemOverhead` in the cdi-config resource (or CDI resource, which manages that resource, if you use the operator to install CDI). Documentation [here|https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md]. Essentially this is to allow for overhead created by filesystems on block devices. Many provisioners will create a block device of the requested size, then put a filesystem on top of that block device.

The actual available storage on that filesystem will then be less than the requested size. Now if you put a disk image file on there that expects the requested size to be available, you will run into issues once the disk starts filling up. So we automatically expand the size of the PVC to take the overhead into account. By default we add 5.5% to account for many filesystems being ext4 which reserves 5% for the root user by default.

Note for block volumes this doesn't happen.

If you don't like this behaviour and don't want it to do that, you can either update the overhead to be 0, and the sizes will match. Or use the pvc stanza instead of the storage stanza and it will simply copy the fields to the pvc as is.

**Comment by jmccormick2001** [comment]
very helpful, thanks.
