### ISSUE TITLE
tests: http server should be installed by the test suite, not 'make cluster-sync'

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#423]
In order to make it possible to run the functional tests against an existing cdi installation, the test dependencies (http server) should be installed as part of test setup, not by make cluster-sync.

**Comment by copejon** [comment]
@aglitke Does the jenkin's have a docker registry to which the file host could be pushed?  If not, we'll have to start publishing the cdi-file-host image to docker hub

**Comment by copejon** [comment]
The straightest route would be to build it into the `make test-functional` target, however I know d/s wants to compile the test individually and run the binary rather than `go test ./...` on the source code.  That means we'd have to bake the file host template into the functional test source.  I'm not 100% on board with that as it means 2 configs would have to be maintained.

**Comment by awels** [comment]
So we actually had a discussion about this, and the problem basically comes down to, do we want to publish the containers needed for the functional tests, in this particular case that is the http server for the tests. We made the assumption that if you are running the functional tests you have the source code and thus you can build and install the http server for the tests.

Once we start publishing the http server image we will have to maintain and support it, which is not something I think we want to do. This is why we decided to install the http server during the sync-cluster step instead of during the test-functional step.

**Comment by copejon** [comment]
So perhaps we need to also build the file host in `make build-functests` to guarantee it's available in the local registry

**Comment by awels** [comment]
There is no guarantee there is a local registry for an existing cluster. The local registry is a concept associated with the kubevirtci environment.

**Comment by copejon** [comment]
@awels Okay, it doesn't sound like we have a choice then - we'll need to publish the image as a build artifact.

**Comment by awels** [comment]
@aglitke Seeing the above comments do you think we should start publishing the http server as an artifact or do you think we should require existing clusters to prepare the cluster for the tests if they want to run them?

**Comment by aglitke** [comment]
In this case I can't help but ask "What would kubevirt do? (wwkd)"  They have similar containers (particularly an iscsi demo container that the tests use.

**Comment by aglitke** [comment]
Closing this since the steps for running functional tests against an external cluster is now documented in https://github.com/kubevirt/containerized-data-importer/blob/master/hack/README.md#getting-started-for-developers
