### ISSUE TITLE
if user delete the import-pod accidentally when it's creating, there should be a new pod being created

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#56]
If user delete the import-pod accidentally when it's creating, there should be a new pod being created.
I think currently our controller doesn't have this mechanism, should we add it ?

**Comment by jeffvance** [comment]
It is documented in the main readme to use a deployment to launch the cdi controller:
_Event Sequence
The admin creates the Controller using a Deployment manifest provided in this repo._

**Comment by jeffvance** [comment]
Will using a deployment allow this issue to be closed?

**Comment by shiywang** [comment]
I mean the pod which cdi-controller created.

**Comment by jeffvance** [comment]
Re-launching the importer pod is equivalent to re-starting the copy from the beginning.

If the importer pod is deleted the pv and pvc will remain bound and unavailable. Thus, a new importer pod referencing the same pvc will not run because the pvc is not available.

Today the controller does not monitor the importer pod. So the controller does not know if the importer pod has terminated with an error, or was successfully, or was accidentally deleted. There has been brief discussions to implement an importer pod watch (or similar) so that the controller can discover that pod's state.

The work-around is to 1) delete the pvc which should delete the pv, 2) re-create the pvc.

**Comment by shiywang** [comment]
>There has been brief discussions to implement an importer pod watch (or similar) so that the controller can discover that pod's state.

Yes, that's what I mean, maybe we can add it in the future

**Comment by copejon** [comment]
Carrying over to #83 and closing.  Once pod monitoring is implemented, we'll have the flexibility to handle these kinds of failures.
