### ISSUE TITLE
Pod import's pod status flaps between Running and Failed breaking retry logic

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#642]
/kind bug

**What happened**:

#495 introduced special logic that marks a pod as failed on the PVC annotation when the pod has not in fact failed.  Instead we're interpreting the Pod's phase as failed because a container failed, even though the pod's status is still Running. 

We have 'restartPolicy: OnFailure' set on our import pods.  This means a container can fail, but will be retried. That's why the pod's phase remains Running. 

So, what we have now is a PVC that will move to a finalized "Failed" state, and then flap back over to Running or Succeeded later on if a subsequent retry of the pod's container completes successfully. 

**What you expected to happen**:

Once the PVC is marked as Failed, I wouldn't expect it to magically go back to running or succeeded later on. 

**Anything else we need to know?**:

This impacts DataVolumes as well. Since DataVolumes derive their phase from the PVC's annotation's pod phase, DataVolumes flap back and forth between failed and succeeded as well under some circumstances. This issue was discovered because it is causing issues with DataVolume integration with KubeVirt.

**Comment by davidvossel** [comment]
This is actually pretty bad now that I'm looking at it in more detail.

this code in import-controller.go ensures that the PVC's annotation nearly **always** transition to failed briefly when the import pod is created regardless if a failure is occurring or not.  Essentially we move to a "Failed" state immediately after posting the Pod while it is "waiting"

```
                //this is for a case where the import container is failing and the restartPolicy is OnFailure. In such case
                //the pod phase is "Running" although the container state is Waiting. When the container recovers, its state
                //changes back to "Running".
                if pod.Status.ContainerStatuses != nil && pod.Status.ContainerStatuses[0].State.Waiting != nil {
                        anno[AnnPodPhase] = string(v1.PodFailed)
                }
```

**Comment by awels** [comment]
Looks like PR #644 fixes this?

**Comment by mhenriks** [comment]
@awels I wouldn't say that #644 exactly fixes this.  Definitely fixes part of the problem.  But we will still go into `Failed` state when an import pod is in a failure/retry loop.  And I don't think @davidvossel wants that.  And I agree.  Failure should be a terminal condition.

Given that import pods are `RetryOnError` so the pod phase will never really be `Failed` and the KubeVirt controller deletes/recreates datavolumes that are `Failed` open questions are:

If/when should an import be considered "failed?"  After 10 retries?  100 retries?  Something else?

If/when should KubeVirt should delete/recreate a "failed" datavolume?

**Comment by mhenriks** [comment]
cc @aglitke @j-griffith

**Comment by j-griffith** [comment]
> If/when should an import be considered "failed?" After 10 retries? 100 retries? Something else?

I'm not sure what the best answer is here, the initial bug was that we "failed" and that for a K8s system that was unexpected or undesirable.  Personally, I'm perfectly fine with failing,  and in fact because this is actually more like an application (ie the infrastructure is provisioned) I think it's perfectly reasonable.

I don't like the retry n times approach so much, it just feels in between to me and I'm unclear how that actually fixes this problem anyway.

> If/when should KubeVirt should delete/recreate a "failed" datavolume?
If we want to keep the retry behavior as is, I think I should abandon the image retryOnError approach and actually implement our own logic inside the DV controller.  The DV would still never fail, but it would continue deleting/recreating PVCs/PODs etc)

I'll look at it this week-end, maybe we can chat about it Monday?

**Comment by j-griffith** [comment]
@mhenriks @davidvossel Setting aside the discussion about if/when to fail; one thing I was wondering about; why do we mess with the DV status so much at all?  Rather than feeding it updates like scheduling, importing etc; what if we just used a simple pending and succeeded (or ready) status.  I realize the transitions might be useful but the other thought is that rather than allowing things to go back and forth, what if we just made it a one way process instead.

So (even if we keep *more* phases) in the import case for example; a DV could go from "pending->scheduled->in-progress;  once it reaches that stage there are only two valid transitions, either "complete" or "failed".

We can still gather more info about what's going on with the events in DV describe so we still provide feedback the user about what's happening.   I can propose a change depending on what you all think.

**Comment by davidvossel** [comment]
> what if we just made it a one way process instead

previously the DV process was to follow the phase of the pod. that still works even with retry on failure. The problem is that code (which i in-lined in a previous comment) that tries to infer the pods phase based on the container's status.  Essentially, we're recording the import/clone pod's phase as something that it isn't. That's why we're having issues.

**Comment by davidvossel** [comment]
This is still a problem. The datavolume status goes to Failed and then flaps back to Importing and even later to Success after it Failed.

Failed and success need to be finalized states. Use a condition to indicate there are issues with importing/cloning that involve retries.

**Comment by awels** [comment]
/remove-lifecycle stale
Still an issue, but hopefully soon we will be in a position to fix it.
