### ISSUE TITLE
apiserver complains about missing openapi spec for upload.cdi.kubevirt.io

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerized-data-importer#666]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Aggregated apiservers are queried by the apiserver for an openapi spec. The spec is that added to `/openapi/v2` in the apiserver.  If no spec is served recurring errors like this can be found in the apiserver logs:

```
E0220 08:39:45.922128       1 controller.go:111] loading OpenAPI spec for "v1alpha1.upload.cdi.kubevirt.io" failed with: OpenAPI spec does not exists
E0220 08:40:45.923774       1 controller.go:111] loading OpenAPI spec for "v1alpha1.upload.cdi.kubevirt.io" failed with: OpenAPI spec does not exists
```

We had the same issue in kubevirt. See https://github.com/kubevirt/kubevirt/pull/1930 and https://github.com/kubevirt/kubevirt/pull/2037 on how this can be fixed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
@mhenriks can you take a look at this?

**Comment by rmohr** [comment]
I am not entirely sure if this is the issue here but I think so: @karmab reported on #virtualization that listing apiserver resources failed from the k8s discovery client (which we use in kibevirt-operator):

```
ERROR: logging before flag.Parse: I0416 15:55:04.790350       1 application.go:147] Error determining cluster type: unable to retrieve the complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the server is currently unable to handle the request
```

We don't do anything CDI specific here. We only run `clientset.DiscoveryClient().ServerResources()` in our code. When @karmab removed CDI, the kubevirt-operator succeeded with listing the resources.

**Comment by karmab** [comment]
as a a side effect of this, ocp dashboard is full of the following messages:

```
API server is returning errors for 100% of requests for GET /apis/upload.cdi.kubevirt.io/v1alpha1
```

**Comment by mhenriks** [comment]
@rmohr @karmab the problem in the OCP 4 environment is that the CDI apiserver does not return its path list when getting the `/` URI.  Basically, it is missing the equivalent of [1] in KubeVirt.  Because of that, the aggregation layer is not even attempting to get the `/apis/upload.cdi.kubevirt.io/v1alpha1` URI (which is implemented).

Interestingly, this is not an issue in k8s 1.13.3 or OS 3.11.

As far as I can tell, `clientset.DiscoveryClient().ServerResources()` does not touch `/openapi/v2`.  So I will fix the `/` problem but leave this issue open to address `/openapi/v2` later.

I will also add that we may want to think about having the KubeVirt operator be more resilient to misbehaving api servers.

[1] https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/api.go#L289-L305

**Comment by rmohr** [comment]
> I will also add that we may want to think about having the KubeVirt operator be more resilient to misbehaving api servers.

I am not sure what we should do in this case. We need to discover resources on the apiserver and the apiserver returns a `5XX` code, which means that something on the server is wrong. Handling situations gracefully where you don't get critical information because of a `5XX` sounds not easy to solve.

**Comment by mhenriks** [comment]
>I am not sure what we should do in this case. We need to discover resources on the apiserver and the apiserver returns a 5XX code, which means that something on the server is wrong. Handling situations gracefully where you don't get critical information because of a 5XX sounds not easy to solve.

It looks like KubeVirt is invoking the discovery stuff in order to figure out if the operator is running in OpenShift.  So, why not limit the check to an OpenShift specific API server?  For example, in the CDI Operator, before attempting to modify the privileged SecurityContextConstraint, it does a get.  If get returns `IsNotFound()` or IsNoMatchError() it assumes not on OpenShift.   If any other error occurs, the operation will be retried.

**Comment by rmohr** [comment]
Created a PR to handle it on the kubevirt side gracefully with the discovery client. Turns out that discovery fails too if a registered aggregated apiserver is not available: https://github.com/kubevirt/kubevirt/pull/2210
