### ISSUE TITLE
Provide example docs for (dynamic ?) PV storage creation for DataVolume's PVCs

### ISSUE THREAD

**Issue by olberger** [kubevirt/containerized-data-importer#776]
It looks like the design of DataVolumes relies on some dynamic mechanism for binding PVCs to PVs, or on the cluster admin to have already provided a suitable PV.

For instance https://kubevirt.io/2018/CDI-DataVolumes.html relies on OpenShift providing "dynamic provisioning for storage running OpenShift Cloud Storage (GlusterFS)"...

However it is not really obvious to deploy such PVs with a minimal Kubernetes cluster (plain kubeadm init on single node Linux machine), by just reading KubeVirt / CDI docs, IMHO.

I think it would be great to provide a minimal demo/instructions to give hints on either how to install a dynamic PV allocator (local hostpath kind), or just "trivial" PV creation instructions.

Thanks in advance.

**Comment by j-griffith** [comment]
Sure, probably would be good to add some wording in the top of the README that we do NOT provide a storageClass but rather expect an SC (either dynamic provisioning or otherwise) be available already.

**Comment by awels** [comment]
Technically we don't require a storage class at all. just an existing PV that will match the PVC request that is generated by the data volume. The range of possible ways of creating a PV is huge, and we didn't want to prescribe what the user should do in order to create one.

I guess we could create a document with different 'tiers' of examples.
1. Single node testing cluster, with hostPath dynamic PV(C) creation
2. Single or multi node local volume cluster (with the WaitForFirstConsumer fun).
3. Multi node cluster, with shared storage like glusterfs or ceph.

**Comment by olberger** [comment]
At least making this explicit in the docs would be a good start, sure (like reusing these wordings, maybe). Of course more detailed tuto (or blog post) would be great.

Thanks for caring.
